site_name: evenoddsjy
site_description: test desc
site_author: Sanjay Soundarajan

repo_url: https://github.com/megasanjay/evenoddsjy
edit_uri: https://github.com/megasanjay/evenoddsjy/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
